export * from '../pages/libreta/libreta'
export * from '../pages/todo/todo'
export * from '../pages/nuevo-contacto/nuevo-contacto'
export * from '../pages/ver-contacto/ver-contacto'
export * from '../pages/nuevo-todo/nuevo-todo'
export * from '../pages/ver-todo/ver-todo'